import type { Metadata } from "next";
import localFont from "next/font/local";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';  
import "./globals.css";
import './modalStyles.css'
import BottomNavbar from "@/components/BottomNavbar";
import TopNavbar from "@/components/TopNavbar";
import Footer from "@/components/Footer";
import ModalInitializer from "@/components/ModalInitializer";
import { SearchProvider } from "@/context/SearchContext";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <SearchProvider>
      <html lang="en">
        <body className="bg-primary antialiased flex flex-col min-h-screen">
        <ModalInitializer />
          <TopNavbar /> 
          <main className="flex-grow pb-20 md:pb-0">{children}</main>
          <Footer /> 
  <BottomNavbar />
        </body>
      </html>
      </SearchProvider>
    </ClerkProvider>
  );
}